# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calibrate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calibrate(object):
    def setupUi(self, Calibrate):
        Calibrate.setObjectName("Calibrate")
        Calibrate.resize(1920, 1080)
        Calibrate.setStyleSheet("backGround:black")
        self.bt_back = QtWidgets.QPushButton(Calibrate)
        self.bt_back.setGeometry(QtCore.QRect(40, 1020, 75, 23))
        self.bt_back.setStyleSheet("color:white")
        self.bt_back.setObjectName("bt_back")

        self.retranslateUi(Calibrate)
        QtCore.QMetaObject.connectSlotsByName(Calibrate)

    def retranslateUi(self, Calibrate):
        _translate = QtCore.QCoreApplication.translate
        Calibrate.setWindowTitle(_translate("Calibrate", "Form"))
        self.bt_back.setText(_translate("Calibrate", "返回"))
