# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomePage(object):
    def setupUi(self, HomePage):
        HomePage.setObjectName("HomePage")
        HomePage.resize(1920, 1080)
        self.videoLable = QtWidgets.QLabel(HomePage)
        self.videoLable.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.videoLable.setStyleSheet("background:transparent")
        self.videoLable.setObjectName("videoLable")
        self.layoutWidget = QtWidgets.QWidget(HomePage)
        self.layoutWidget.setGeometry(QtCore.QRect(300, 590, 241, 291))
        self.layoutWidget.setObjectName("layoutWidget")
        self.options = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.options.setContentsMargins(0, 0, 0, 0)
        self.options.setObjectName("options")
        self.bt_start = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_start.sizePolicy().hasHeightForWidth())
        self.bt_start.setSizePolicy(sizePolicy)
        self.bt_start.setStyleSheet(".QPushButton{color:white;\n"
"border-image:url(./ui/resources/HomePageBtnBg.png);\n"
"font-family:微软雅黑;\n"
"font-size:16px}\n"
".QPushButton:hover{color:#79d9ff;\n"
"border-image:url(./ui/resources/HomePageBtnBg_hover.png);\n"
"font-size:16px}")
        self.bt_start.setObjectName("bt_start")
        self.options.addWidget(self.bt_start)
        self.bt_records = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_records.sizePolicy().hasHeightForWidth())
        self.bt_records.setSizePolicy(sizePolicy)
        self.bt_records.setStyleSheet(".QPushButton{color:white;\n"
"border-image:url(./ui/resources/HomePageBtnBg.png);\n"
"font-family:微软雅黑;\n"
"font-size:16px}\n"
".QPushButton:hover{color:#79d9ff;\n"
"border-image:url(./ui/resources/HomePageBtnBg_hover.png);\n"
"font-size:16px}")
        self.bt_records.setObjectName("bt_records")
        self.options.addWidget(self.bt_records)
        self.bt_setting = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_setting.sizePolicy().hasHeightForWidth())
        self.bt_setting.setSizePolicy(sizePolicy)
        self.bt_setting.setStyleSheet(".QPushButton{color:white;\n"
"border-image:url(./ui/resources/HomePageBtnBg.png);\n"
"font-family:微软雅黑;\n"
"font-size:16px}\n"
".QPushButton:hover{color:#79d9ff;\n"
"border-image:url(./ui/resources/HomePageBtnBg_hover.png);\n"
"font-size:16px}")
        self.bt_setting.setObjectName("bt_setting")
        self.options.addWidget(self.bt_setting)
        self.bt_quit = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_quit.sizePolicy().hasHeightForWidth())
        self.bt_quit.setSizePolicy(sizePolicy)
        self.bt_quit.setStyleSheet(".QPushButton{color:white;\n"
"border-image:url(./ui/resources/HomePageBtnBg.png);\n"
"font-family:微软雅黑;\n"
"font-size:16px}\n"
".QPushButton:hover{color:#79d9ff;\n"
"border-image:url(./ui/resources/HomePageBtnBg_hover.png);\n"
"font-size:16px}")
        self.bt_quit.setObjectName("bt_quit")
        self.options.addWidget(self.bt_quit)
        self.label = QtWidgets.QLabel(HomePage)
        self.label.setGeometry(QtCore.QRect(90, 400, 662, 129))
        self.label.setStyleSheet(".QLabel{background:url(./ui/resources/赛博射击屋.png)}\n"
".QLabel:hover{background:url(./ui/resources/赛博射击屋_hover.png)}")
        self.label.setObjectName("label")

        self.retranslateUi(HomePage)
        QtCore.QMetaObject.connectSlotsByName(HomePage)

    def retranslateUi(self, HomePage):
        _translate = QtCore.QCoreApplication.translate
        HomePage.setWindowTitle(_translate("HomePage", "Form"))
        self.videoLable.setText(_translate("HomePage", "TextLabel"))
        self.bt_start.setText(_translate("HomePage", "开始"))
        self.bt_records.setText(_translate("HomePage", "记录"))
        self.bt_setting.setText(_translate("HomePage", "设置"))
        self.bt_quit.setText(_translate("HomePage", "退出"))
        self.label.setText(_translate("HomePage", "TextLabel"))
