# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlayPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlayPage(object):
    def setupUi(self, PlayPage):
        PlayPage.setObjectName("PlayPage")
        PlayPage.resize(1920, 1080)
        PlayPage.setStyleSheet("backGround:black;\n"
"color:white;\n"
"font-size:16px;\n"
"font-family:微软雅黑")
        self.hitpointLabel = QtWidgets.QLabel(PlayPage)
        self.hitpointLabel.setGeometry(QtCore.QRect(800, 120, 200, 20))
        self.hitpointLabel.setStyleSheet("background:transparent;\n"
"color:white")
        self.hitpointLabel.setObjectName("hitpointLabel")
        self.scoreLabel = QtWidgets.QLabel(PlayPage)
        self.scoreLabel.setGeometry(QtCore.QRect(800, 160, 200, 20))
        self.scoreLabel.setStyleSheet("background:transparent;\n"
"color:white")
        self.scoreLabel.setObjectName("scoreLabel")
        self.countLabel = QtWidgets.QLabel(PlayPage)
        self.countLabel.setGeometry(QtCore.QRect(1620, 260, 100, 96))
        self.countLabel.setStyleSheet("color:#7c7c7c;\n"
"background:transparent")
        self.countLabel.setObjectName("countLabel")
        self.accuracyLabel = QtWidgets.QLabel(PlayPage)
        self.accuracyLabel.setGeometry(QtCore.QRect(1620, 360, 100, 96))
        self.accuracyLabel.setStyleSheet("color:#7c7c7c;\n"
"background:transparent")
        self.accuracyLabel.setObjectName("accuracyLabel")
        self.avgscoreLabel = QtWidgets.QLabel(PlayPage)
        self.avgscoreLabel.setGeometry(QtCore.QRect(1620, 460, 100, 96))
        self.avgscoreLabel.setStyleSheet("color:#7c7c7c;\n"
"background:transparent")
        self.avgscoreLabel.setObjectName("avgscoreLabel")
        self.headshotRateLabel = QtWidgets.QLabel(PlayPage)
        self.headshotRateLabel.setGeometry(QtCore.QRect(1620, 560, 100, 96))
        self.headshotRateLabel.setStyleSheet("color:#7c7c7c;\n"
"background:transparent")
        self.headshotRateLabel.setObjectName("headshotRateLabel")
        self.bt_reset = QtWidgets.QPushButton(PlayPage)
        self.bt_reset.setGeometry(QtCore.QRect(1550, 810, 239, 68))
        self.bt_reset.setStyleSheet(".QPushButton{color:white;\n"
"border-image:url(./ui/resources/HomePageBtnBg.png);\n"
"font-family:微软雅黑;\n"
"font-size:16px}\n"
".QPushButton:hover{color:#79d9ff;\n"
"border-image:url(./ui/resources/HomePageBtnBg_hover.png);\n"
"font-size:16px}")
        self.bt_reset.setObjectName("bt_reset")
        self.bt_save = QtWidgets.QPushButton(PlayPage)
        self.bt_save.setGeometry(QtCore.QRect(1550, 885, 239, 68))
        self.bt_save.setStyleSheet(".QPushButton{color:white;\n"
"border-image:url(./ui/resources/HomePageBtnBg.png);\n"
"font-family:微软雅黑;\n"
"font-size:16px}\n"
".QPushButton:hover{color:#79d9ff;\n"
"border-image:url(./ui/resources/HomePageBtnBg_hover.png);\n"
"font-size:16px}")
        self.bt_save.setObjectName("bt_save")
        self.bt_back = QtWidgets.QPushButton(PlayPage)
        self.bt_back.setGeometry(QtCore.QRect(1550, 960, 239, 68))
        self.bt_back.setStyleSheet(".QPushButton{color:white;\n"
"border-image:url(./ui/resources/HomePageBtnBg.png);\n"
"font-family:微软雅黑;\n"
"font-size:16px}\n"
".QPushButton:hover{color:#79d9ff;\n"
"border-image:url(./ui/resources/HomePageBtnBg_hover.png);\n"
"font-size:16px}")
        self.bt_back.setObjectName("bt_back")
        self.bg_label = QtWidgets.QLabel(PlayPage)
        self.bg_label.setGeometry(QtCore.QRect(1480, 50, 372, 754))
        self.bg_label.setStyleSheet(".QLabel{background:url(./ui/resources/PlayPageBg.png);}\n"
".QLabel:hover{background:url(./ui/resources/PlayPageBg_hover.png);}")
        self.bg_label.setText("")
        self.bg_label.setObjectName("bg_label")
        self.targetLabel = QtWidgets.QLabel(PlayPage)
        self.targetLabel.setGeometry(QtCore.QRect(790, 100, 600, 880))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetLabel.sizePolicy().hasHeightForWidth())
        self.targetLabel.setSizePolicy(sizePolicy)
        self.targetLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.targetLabel.setStyleSheet("color:white;\n"
"")
        self.targetLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.targetLabel.setObjectName("targetLabel")
        self.camLabel = QtWidgets.QLabel(PlayPage)
        self.camLabel.setGeometry(QtCore.QRect(100, 100, 600, 880))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camLabel.sizePolicy().hasHeightForWidth())
        self.camLabel.setSizePolicy(sizePolicy)
        self.camLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.camLabel.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.camLabel.setStyleSheet("color:white;\n"
"")
        self.camLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.camLabel.setObjectName("camLabel")
        self.bg_label.raise_()
        self.accuracyLabel.raise_()
        self.avgscoreLabel.raise_()
        self.headshotRateLabel.raise_()
        self.bt_reset.raise_()
        self.bt_save.raise_()
        self.bt_back.raise_()
        self.countLabel.raise_()
        self.targetLabel.raise_()
        self.camLabel.raise_()
        self.hitpointLabel.raise_()
        self.scoreLabel.raise_()

        self.retranslateUi(PlayPage)
        QtCore.QMetaObject.connectSlotsByName(PlayPage)

    def retranslateUi(self, PlayPage):
        _translate = QtCore.QCoreApplication.translate
        PlayPage.setWindowTitle(_translate("PlayPage", "Form"))
        self.hitpointLabel.setText(_translate("PlayPage", "命中点："))
        self.scoreLabel.setText(_translate("PlayPage", "分数："))
        self.countLabel.setText(_translate("PlayPage", "计数："))
        self.accuracyLabel.setText(_translate("PlayPage", "准确率："))
        self.avgscoreLabel.setText(_translate("PlayPage", "平均分："))
        self.headshotRateLabel.setText(_translate("PlayPage", "爆头率："))
        self.bt_reset.setText(_translate("PlayPage", "重置"))
        self.bt_save.setText(_translate("PlayPage", "保存"))
        self.bt_back.setText(_translate("PlayPage", "主菜单"))
        self.targetLabel.setText(_translate("PlayPage", "未检测到靶子"))
        self.camLabel.setText(_translate("PlayPage", "请稍等..."))
